name: 'Deploy'
description: 'Deploy release assets to desired environment'
inputs:
  GATEWAY_URL:
    description: 'WSD Gateway URL to trigger deployment'
    required: true
  GATEWAY_SECRET:
    description: 'WSD Gateway Secret to sign the payload'
    required: true
runs:
  using: "composite"
  steps:
    - name: Trigger WSD Gateway
      uses: actions/github-script@v7
      with:
        script: |
          const crypto = require('crypto');
          const getHmac = ( key, str ) => crypto.createHmac ( 'sha1', key ).update ( str ).digest ( 'hex' );
          const body = JSON.stringify( context.payload );
          const resp = await fetch( inputs.GATEWAY_URL , {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
              "x-hub-signature": 'sha1=' + getHmac ( inputs.GATEWAY_SECRET, body ),
              "x-github-event": "push",
            },
            body: body,
          });
          const message = await resp.text();
          if ( message.code !== 202 ) {
            core.setFailed( message );
            throw new Error( message );
          }