name: Deploy [STAGING] - DocAuto v2

on:
  workflow_call:

jobs:
  deploy-staging:
    name: Deploy [STAGING] - DocAuto v2
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
      - name: Trigger Webhook
        uses: actions/github-script@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GATEWAY_URL: https://staging-gateway.priipcloud.com/api/v2.0/deploy/webhook/github
          GATEWAY_SECRET: ${{ secrets.GATEWAY_SECRET }}
        with:
          script: |
            console.log(context, process.env)
            
            const crypto = require('crypto');
            const getHmac = ( key, str ) => crypto.createHmac ( 'sha1', key ).update ( str ).digest ( 'hex' );
            const body = JSON.stringify({ 
                repository: process.env.GITHUB_REPOSITORY,
                sender: context.actor,
                ref: context.ref
              });
            
            const response = await fetch( process.env.GATEWAY_URL , {
              method: "POST",
              headers: { 
                "Content-Type": "application/json",
                "x-hub-signature": 'sha1=' + getHmac ( process.env.GATEWAY_SECRET, body ),
                "x-github-event": "push",
              },
              body: body,
            });
            
            console.log(await response.text());