name: Deploy [SANDBOX] - DocAuto v2

on:
  workflow_call:

jobs:
  deploy-staging:
    name: Deploy [SANDBOX] - DocAuto v2
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: deployment
        with:
          token: '${{ github.token }}'
          ref: ${{ github.ref_name }}
          environment-url: https://sandbox-docauto.wallstreetdocs.com/webide#/
          environment: sandbox

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          environment-url: ${{ steps.deployment.outputs.environment_url }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: 'success'

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          environment-url: ${{ steps.deployment.outputs.environment_url }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: 'failure'