name: Deploy Release
run-name: Deploying ${{ github.ref }} to ${{ inputs.ENVIRONMENT }}

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        description: Select Environment to deploy to
        required: true
        type: environment

env:
  ENVIRONMENT: ${{ inputs.ENVIRONMENT }}

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy STAGING
        if: ${{ env.ENVIRONMENT == 'staging' }}
        uses: ./.github/actions/push
        with:
          GATEWAY_URL: 'https://staging-gateway.priipcloud.com/api/v2.0/deploy/webhook/github'
          GATEWAY_SECRET: ${{ secrets.GATEWAY_SECRET }}

      - name: Deploy SANDBOX
        if: ${{ env.ENVIRONMENT == 'sandbox' }}
        uses: ./.github/actions/push
        with:
          GATEWAY_URL: 'https://uat-gateway.priipcloud.com/api/v2.0/deploy/webhook/github'
          GATEWAY_SECRET: ${{ secrets.GATEWAY_SECRET }}

      - name: Deploy UAT
        if: ${{ env.ENVIRONMENT == 'uat' }}
        uses: ./.github/actions/push
        with:
          GATEWAY_URL: 'https://uat-gateway.priipcloud.com/api/v2.0/deploy/webhook/github'
          GATEWAY_SECRET: ${{ secrets.GATEWAY_SECRET }}

      - name: Deploy PRODUCTION
        if: ${{ env.ENVIRONMENT == 'production' }}
        uses: ./.github/actions/push
        with:
          GATEWAY_URL: 'https://gateway.priipcloud.com/api/v2.0/deploy/webhook/github'
          GATEWAY_SECRET: ${{ secrets.GATEWAY_SECRET_PROD }}