name: Pull request

on:
  pull_request:

jobs:

  build:

    uses: ./.github/workflows/stage-build.yml
    with:
      ENABLE_QUALITY_GATE: true
    secrets: inherit

  notify:

    runs-on: ubuntu-latest
    needs: build
    steps:

      # Send teams notification
      - name: NOTIFY Send Teams notification
        uses: toko-bifrost/ms-teams-deploy-card@master
        if: always()
        with:
          github-token: ${{ github.token }}
          webhook-uri: ${{ secrets.MICROSOFT_TEAMS_WEBHOOK_URI }}