name: Tag Deployment Test

on:
  workflow_call:

jobs:

  check-if-tag:
    name: Check if current branch is a tag
    runs-on: ubuntu-latest
    steps:
      - name: Fail if branch is not a tag
        run: |
          echo ${{ github.ref }}
          if [[ ! "${{ github.ref }}" =~ ^refs\/tags\/.+$ ]]; then
            echo "Selected branch is not a tag; exiting..."
            exit 1
          fi

  get-release-tag:
    name: Check if tag has a release
    needs: check-if-tag
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Get corresponding release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          FOUND_RELEASES=$(gh release list --json tagName,name --jq '.[] | select(.tagName == "${{ github.ref_name }}")')
          if [[ "$( echo ${FOUND_RELEASES} | wc -l)" -lt 1 ]]; then
            echo "No releases found for tag '${{ github.ref_name }}'"
            exit 1
          fi